# Generated by Django 5.1.4 on 2025-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(
                choices=[
                    ("BT", "Bachelor of Technology"),
                    ("BBA", "Bachelor of Business Administration"),
                    ("BCom", "Bachelor of Commerce"),
                ],
                default="BT",
                max_length=4,
            ),
            preserve_default=False,
        ),
    ]
